doctrine:
    orm:
        mappings:
            CryptoBundle:
                is_bundle: true
                type: annotation
                dir: 'src/Entity'
                prefix: 'ICS\CryptoBundle\Entity'
                alias: Crypto
    