navigation:
  navbars:
    main:
      items:
        crypto-homepage:
          lib: crypto
          icon: fa fa-home
          route: ics_crypto_homepage
          order: 10
        items1:
          lib: 'Opération'
          icon: fa fa-coins
          route: ics_crypto_homepage
          roles: []
        items2:


    sidebar: 
      brand: Accueil
      brandRoute: ics_crypto_homepage
      brandIcon: ''
      brandImage: ''
      type: sidebar
      searchenabled: false
      searchroute: search
      color: dark
      fixed: sticky
      items:
        items1:
          lib: 'Opération'
          icon: fa fa-home
          route: ics_crypto_homepage
          roles: []
        items2:
          lib: 'Exchange'
          icon: fa fa-home
          route: ics_crypto_homepage
          roles: []
        items3:
          lib: 'Générale'
          icon: fa fa-home
          route: ics_crypto_homepage
          roles: []
        items4:
          lib: 'Import'
          icon: fa fa-home
          route: ics_crypto_homepage
          roles: []
        items5:
          lib: 'Export'
          icon: fa fa-home
          route: ics_crypto_homepage
          roles: []
        items6:
          lib: 'Nouveauté'
          icon: fa fa-home
          route: ics_crypto_homepage
          roles: []
